baseurl = "https://insileco.github.io/"
title = "inSileco"
theme = "minimal"
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "Rscript/sessionInfo\\.Rmd"]
enableEmoji = true
copyright = "2017-2024 inSileco"
math = false
pygmentsUseClasses = false
summaryLength = 25
# relativeURLs = true


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            footnote = true
    [markup.highlight]
        lineNos = true
        noClasses = false
    [markup.tableOfContents]
        endLevel = 2
        startLevel = 2

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
    [languages.en.params]
        translationText = "Available translation: "
        flag = ":uk:"
  [languages.fr]
    languageCode = "fr-ca"
    languageName = "Français"
    weight = 2
    [languages.fr.params]
        translationText = "Traduction disponible: "
        flag = ":fr:"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Resources"
    url = "/resource/"
[[menu.main]]
    name = "Posts"
    url = "/post/"
[[menu.main]]
    name = "Consulting"
    url = "https://insilecoinc.github.io/"

[[menu.icon]]
    url = "/"
    name = "fas fa-home"
    weight = 1
[[menu.icon]]
    url = "https://github.com/inSileco/"
    name = "fab fa-github"
    weight = 2
[[menu.icon]]
    url = "https://twitter.com/inSileco/"
    name = "fab fa-twitter"
    weight = 3
[[menu.icon]]
    url = "https://insileco.github.io/index.xml"
    name = "fas fa-rss"
    weight = 4

[params]
    author = "inSileco"
    description = "Codes, ideas and methods in ecology"
    githubUsername = "#inSileco"
    twitterUsername = "inSileco"
    font = "Lato"
    accent = "#3fb3b2"
    showBorder = true
    backgroundColor = "white"
    highlight = false
    css = [
        "https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.206/distr/fira_code.css",
        "/css/academicons.min.css",
        "/css/main.css",
        "/css/syntax.css"
    ]
    js = [
        "/js/codecopypaste.js"
    ]

[taxonomies]
    tag = "tags"
    category = "categories"
    rpkg = "rpkgs"
