---
title: "inSilecoMisc 0.3.0"
author: [kevin]
date: 2020-03-17
tags: [R, data visualization]
tweet: "Empty your R plots!"
draft: true
estime: 10
output:
  rmarkdown::html_page:
    toc: true
    fig_width: 3
    dev: svg
---


# inSilecoMisc

inSilecoMisc is an R :package: almost four years ago now,
that included a bunch of miscellenous function (same philosophy as [Hmisc](https://github.com/harrelfe/Hmisc)). Initatially it was a pckage
to store function that I thought was useful and a good opportunity to
create another package for the sake of practcingd

Since them, it goes on and off. But also it is an opportunity for little project just leeanr more.

I have alre `r htmltools::HTML("{{ ref '/content/post/current/dfTemplate.Rmd' }}")`


This was simply, basically to many functions for but not a package with a specific goal.


Also



Last week end I decided to give it a good cleanup since I haven't touch it for a few months. For this cleanup I had a few project but baisically

1. use travis to deplot the website

2.


 d and develop the website on Travis.
Well a;ll good.



```{R}
library("inSilecoMisc")
packageVersion("inSilecoMisc")
```



in the vein of Hmisc




# Use Travis to deplot the website

I



keepLetters()


See previous post for data template




# New feature `tblDown()`

This is something . Of course if you are using R Markkwon but if your are not
if a couple of manipulations. `tblDown()` makes it very easy.

Caption written using with a non exported function



See outpout in zip file.s





<details>
<summary>
  <h4>
    <i class="fa fa-chevron-right" aria-hidden="true"></i>Session info
    <i class="fa fa-cogs" aria-hidden="true"></i>
  </h4>
</summary>

```{R sessionInfo}
sessionInfo()
```
</details>
