---
title: "Custom tick marks with R's base graphics system"
author: [kevin]
reviewer: [willian]
date: 2020-08-26
tags: [R, ticks, axes]
rpkgs: [graphics]
tweet: "Custom tick marks with R's base graphics system"
draft: false
review: true
rbloggers: false
estime: 9
output:
  rmarkdown::html_page:
    toc: true
    fig_width: 3
    dev: svg
---


```{R setup, include = FALSE}
set.seed(77)
source('../../codeChunkSetUp.R')
```

## Context

If you are using R's base graphics system for your plots and if you like
customizing your plots, you may have already wondered how to custom the tick
marks of your plots! I do that quite a lot and I thought it would be worth
explaining how I do so. Let's consider the following plot,

```{R prob}
cx <- seq(0, 2, 0.1)
cy <- cx + .5*rnorm(length(cx))
plot(cx, cy)
```

By default, `plot.default` internally has its way to decide where tick marks
should be added. It is always a good default choice, but sometimes not the one
you're looking for. Fortunately, the core package `graphics` includes all what
you need to custom the tick marks and so, without further ado, let's custom our
ticks!


## Remove axes and add them back

The first step is to remove all axes. There are basically two ways. One option
is to use `xaxt = "n"` and `yaxt = "n"` to selectively remove the x-axis and
the y-axis, respectively.

```{R}
plot(cx, cy, xaxt = "n")
```

```{R}
plot(cx, cy, xaxt = "n", yaxt = "n")
```

The second option is to set `axes` to `FALSE` in `plot()`:

```{R}
plot(cx, cy, axes = FALSE)
```

As you can see, when `axes = FALSE` the box is also removed and you can actually add it back with `box()`:

```{R}
plot(cx, cy, axes = FALSE)
box()
```

and change its style, if desired:


```{R}
plot(cx, cy, axes = FALSE)
box(bty = "l")
```


That being said, let's only remove the x-axis for the moment and add ticks at 0,
0.5, 1, 1.5 and 2 to the x-axis using `axis()`:

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5))
```

I can easily change the labels if values on the axis are not the ones that
should be displayed, e.g.

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = letters[1:5])
```



## Second set of tick marks

Now, let's add a second set tick marks! This can be done by calling `axis()` one
more time.

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5))
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA)
```

As you may have noticed, I use `setdiff()` to select the complementary set of
ticks. I think it is an efficient of proceeding: I first select the finest gap
between two ticks (here 0.1) and create the sequence with `seq()`, then create
the main set of tick marks and finally use `setdiff()` will to add the
remaining tick marks. Also here, as I don't want to add extra labels, I just set
the labels to `NA`.


## Remove the extra line

The main reason why I adjust the tick marks on my plots is because `axis()` and
`box()` add lines that partially overlap (this is also true when you use the
default behavior of `plot()`): the lines that comes along with the ticks

```{R}
plot(cx, cy, axes = FALSE)
axis(2)
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5))
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA)
```

overlap with the box

```{R}
plot(cx, cy, axes = FALSE)
box()
```

This may frequently goes unnoticed, but I personally tend to notice such overlap
this and it annoys me... Anyway, one way to handle this is to set the line width
to 0 in `axis()`.


```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd = 0)
```

and then to set the line with of the ticks, controlled by `lwd.ticks`, to
something greater than 0

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, lwd.ticks = 1)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd = NA, lwd.ticks = 1)
box()
```

Note that if you only wish to remove the marks you can use `tick = FALSE`.

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), tick = FALSE)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, tick = FALSE)
box()
```

But if you just want to get rid of the extra line, but not the ticks, then you
need set `lwd` to 0 and `lwd.ticks` to a positive values.



## Custom the ticks

Having done the steps above, you may have realized that fine-tuning `lwd.ticks`
is a good way to custom your tick marks!

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, lwd.ticks = 1.5)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd = 0, lwd.ticks = .5)
box()
```

A second parameter to further customize the tick marks is `tck` that actually
belongs to `par()`


```{R tckinpar}
par(tck = -0.07)
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0,
  lwd.ticks = 1)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd.ticks = 1)
box()
```

but can also be used with `axis()` thanks to the ellipsis (`...`) which allow me
to change it only for one set of ticks


```{R tckinaxis}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, tck = -0.07,
  lwd.ticks = 1)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd.ticks = 1)
box()
```


Moreover, using positive value you can make the tick go up!

```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, tck = 0.07,
  lwd.ticks = 1)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd.ticks = 1)
box()
```

And finally you change many aspect of them, including color then and line type:


```{R}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, lwd.ticks = 1.5, tck = -.07, col = 2, lty = 2)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd.ticks = .5, tck = -.03, col = 3)
box()
```

One more tip, if you need to adjust the position of the tick you would have to
use `mgp` (also documented in `par`) which is a vector of three elements
controlling the following features:

1. the position of the axis labels,
2. the position of the tick labels,
3. the positon on the tick marks.


```{R mgp}
par(mgp = c(2.5, 1.6, 0))
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, lwd.ticks = 1.5,
  tck = -.1, col = 2, lty = 2)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd.ticks = .5, tck = -.03, col = 3)
box()
```

Note that, just as for `tck`, I can use `mgp` in `axis()`. In this example,  it
won't affected the axis labels because they were added by `plot()`.


```{R mgpinaxis}
plot(cx, cy, xaxt = "n")
axis(1, at = seq(0, 2, .5), labels = seq(0, 2, .5), lwd = 0, lwd.ticks = 1.5,
  tck = -.1, col = 2, lty = 2)
axis(1, at = setdiff(cx, seq(0, 2, .5)), labels = NA, lwd.ticks = .5, tck = -.03, col = 3, mgp = c(2.5, 1.6, 0))
box()
```





## Wrap that up in a function

All what I've done above may appear overwhelming at first because you need to
memorize where is what... But once everything gets clear, you would realize that
for most of your plots you need to tweak the same parameters and so that you
can create your own function that would cover your needs. For instance, I often
use a function similar to the one below:

```{R fun}
myaxis <- function(side, all, main, lab = main, col1 = 1, col2 = 1, ...) {
  axis(side, at = main, labels = lab, lwd = 0, lwd.ticks = 1, col = col1, ...)
  axis(side, at = setdiff(all, main), labels = NA, lwd.ticks = .75, tck = -.025,
    col = col2, ...)
}
```

which is basically makes the customization of tick marks very easy!

```{R final}
plot(cx, cy, xaxt = "n", yaxt = "n")
myaxis(1, cx, seq(0, 2, .5))
myaxis(2, seq(-0.5, 2.8, .1), seq(-0.5, 2.5, .5), las = 1)
```

<br>

#### That's all folks :smile:!

<br>

<details>
<summary> Session info <i class="fa fa-cogs" aria-hidden="true"></i> </summary>
```{r sessionInfo}
sessionInfo()
```
</details>
