---
title: "About this website"
---



## About the authors

<br/>

```{r textAuthors, echo=FALSE, results="asis", message=FALSE}
  source("Rscripts/textAuthors.R")
```


## About our blog posts

<br/>

All authors of this blog are ecologists and modelers and therefore inclined to
write blog posts related to both ecology and modeling. As modelers, we use various
computational tools. However, given the current prevalence of
[R](https://www.r-project.org/) among ecologists, we tend to write more about R
than other programming langages. This website it-self is been built with
[Rmarkdown](http://rmarkdown.rstudio.com/rmarkdown_websites.html) which is a very convenient way to write about R.  


Many packages are used throughout this website. Below is the exhaustive list of R packages we've used to generate this website. It includes all R packages
(*i.e.* CRAN and Github packages) required to generate all our blog posts and
the rest of the website. We do our best to keep this list as short as possible. To do so, we do not include packages that will be installed as a dependencies. For instance, we may use several functions included in the *raster* package but as *biomod2* depends on *raster*, we drop *raster* from the list (it will however be installed with *biomod2*).

To make future updates of this list easier, we used the following [gist](https://help.github.com/articles/about-gists/):

<script src="https://gist.github.com/KevCaz/aaa83151e9d12cc07fbe379e2c32a385.js"></script>
