---
title: R in Space - A Series
author: [david, elliot, kevin, nicolas, remi, steve]
reviewer: []
date: 2018-02-21
tags: [R, Viz, Spatial, R in Space]
draft: true
tweet: "R in Space - A Series"
estime: 14
---

## So it begins

A good proportion of people involved in inSileco have one particular expertise
in common: we work extensively with spatial data. This expertise has been
developed through extensive time importing, creating and formatting spatial
data, performing spatial analyses and building static and dynamic spatiual
visualizations.

In this blog post series, we propose an educational tour of spatial possibilities
offered by tools developed in the R environment. This series could thus be used
in an educational setting to learn how to use R in Space!

<!-- The format of the posts will be quite straightforward: each post will begin with
*Post in Brief* section presenting the main functionalities presented in the post,
followed by a *Post in Details* section that goes more in depth for people who may
be more interested in an in-depth understanding of functionalities presented.

Comment DB: I don't know whether that is a realistic wish because I doubt it would be
applicable to all posts
-->

As is our usual habit, rather than creating a series of posts presenting specific
tools, we will first ask a series of explicitly spatial and ecological questions
and go through the possibilities offered by R to play around with spatial tools.

<br/>

## The question

<br/>

## The plan

- R in Space
  - **Resources**
    - Main spatial packages
      - `rgeos`
      - `rgdal`
      - `raster`
      - `sp`
      - `sf`
    - Other packages
      - `maptools`
      - ...
    - Spatial data in R
      - `raster`
      - `sdmpredictors`
      - ...
  - **Beginnings**
    - Spatial object in R
      - `raster`
      - `sp`
      - `sf`
      - `netcdf`? <!-- David w/ NASA data -->
    - Spatial projections
      - Resources (http://spatialreference.org/)
    - Importing spatial objects
      - Shapefiles
      - Geodatabases
      - Coordinates (see creating spatial objects) <!-- need to mention it in importing, but it really should be in creating spatial objects using coordinates data -->
    - Creating spatial objects
      - From coordinates
    - Transforming spatial objects between types
      - `sp` to `sf`
      - `sf` to `sp`
  - **Teens**
    - Spatial modifications...


## What I wrote few months ago

Over the last decade, new softwares have emerged making the creation and
edition of maps accessible to all. Scientists can now readily draw valuable
spatial representations of their work without deep knowledge in mapping
(I recommend the reading of the Nature's article [“Science on the
Map"](http://www.nature.com/news/data-visualization-science-on-the-map-1.17024).
by Zastrow, Mark - 2015. Basic mapping skills should be a part of educational
background of many scientists as maps are often a proper way to expose facts and
thereby a valuable tool to ease the scientific debate. Among the tools available
(see below) some Geographic Information System (GIS) are free, open-source such
as [Quantum GIS](http://qgis.org/en/site/) and [GRASS GIS](http://grass.osgeo.org).
Also, some high-level programming languages such as JavaScript, Python,
or R offer dedicated packages. A couple are listed a couple of softwares:

- [ArcGIS](http://www.arcgis.com/features/)
- [CartoDB](http://cartodb.com)
- [DIVA-GIS](http://www.diva-gis.org)
- [GeoJson](http://geojson.io/#map=2/20.0/0.0)
- [Google Map](https://www.google.fr/maps)
- [Goole Earth](http://www.google.fr/intl/eng/earth/index.html)
- [GRASS](http://grass.osgeo.org)
- [Leaflet](http://leafletjs.com)
- [Mapinfo](http://www.mapinfo.com)
- [Mapnik](http://mapnik.org)
- [PostGIS](http://www.postgis.org)
- [Quantum GIS](http://qgis.org/en/site/)
- [SAGA GIS](http://www.saga-gis.org/en/index.html)
- [TileMill](https://www.mapbox.com/tilemill/)





## Why use R for mapping?

Given the number of tools dedicated to visualization and analyses of spatial
data, it is important that users ask this question and take some time to balance
pros and cons of using R for mapping. According to us, the choice strongly
relies on (i) your ambition in terms of mapping and (ii) your skills in R.
If you aim at creating a good-looking map without analysis and you are not
familiar with R, it does not make any sense to use R only for mapping. But if
you are familiar with R or plan on becoming familiar with it to perform and
replicate spatial analyses in R, you can quickly get a good-looking map (a R
plot basically) and then benefit from the plot system you already know. Also,
when you need tricky spatial analysis, even if you are not familiar with R,
you will doubtlessly may benefit from learning it.


## Reference for R

## Reference for Python

A list: http://carsonfarmer.com/2013/07/essential-python-geo-libraries/
http://geopandas.org/
https://blog.plon.io/geo-data-science/introduction-geo-data-science-python/
https://docs.qgis.org/2.14/en/docs/pyqgis_developer_cookbook/

## Julia

https://github.com/JuliaGeo
