---
title: "rcites, behind the scenes"
author: [kevin]
date: 2018-11-11
tags: [R, package, development]
rpkgs: [devtools]
draft: true
tweet: "First R package to the CRAN"
estime: 15
output:
  rmarkdown::html_page:
    toc: true
    fig_width: 3
    dev: svg
---


A couple of colleagues and I have recently released a R package to the CRAN, [rcites](https://github.com/ibartomeus/rcites), a R client for the [Species+ API](https://api.speciesplus.net/). In the following lines, I would like to
share my experience, few thoughts about R packages as well as valuable resources.



## What is a R package?

In the introduction of his book [R packages](http://r-pkgs.had.co.nz/intro.html),
Hadley Wickham wrote:

> A package bundles together code, data, documentation, and tests, and is easy to share with others.

I like the way the famous R developer presents a package, it is straightforward
and crystal clear. Interestingly enough, it describes what a package **does**,
not what a package **is**. Defining R package is actually harder than I thought!
I remember the first time, I've tried to characterize an R package, I asked
myself a couple of questions and found the answers quite surprising:

- Are R packages extensions available on [CRAN](https://cran.r-project.org/) or [Bioconductor](https://www.bioconductor.org/)? **Not necessarly!**

The answer sounds obvious nowadays with over than [40K R packages on Github](https://rdrr.io/), but 10 years it wasn't. However it is important to notice that an R package that only exists (yet) in your own computer is an R package.

- Should a package have a minimum number of functions? **No**

Even among the most popular packages, the number of package is not a criterion. For instance, [vegan](https://cran.r-project.org/web/packages/vegan/index.html) exports 192 functions (as of version 2.5.2) while [png](https://cran.r-project.org/web/packages/png/) only includes
two functions.

- Should a package be designed to perform a specific analysis? **No**

Two points here. First, R packages do many things: they can turn R into a power
Geographic Information System or make your R session crash each time you load it
(see [trump](https://github.com/romainfrancois/trump))!

So **what is a R package?** Well, my own definition would be something along this
line:

> a set of files that passes the command `R CMD INSTALL`

From this definition, one should understand that a R package does not
any analysis correctly. Rather a package is an organized set of files that
complies to a well-defined set of rules (there are indeed numerous tests!).






## Why create a R package?

This is another crucial question. In [his introduction](http://r-pkgs.had.co.nz/intro.html),
Hadley Wickham emphasized that R packages are a standard way to organize your
project which helps you saving time and ease the code sharing.
Once your are used to create and handle R packages, it becomes natural to use
the standard file organzation to structure your project or something very
similar (see for instance https://nicercode.github.io/blog/2013-04-05-projects/)
and you'll stop using `setwd()`.

Interestingly enough, one of the main reason of creating a package is for
efficiency purposes not necessarily to submitted it to the CRAN. I do think
this point is extremely important because if you start using packages for your
analysis, the day you decide that you want to actually share the set of functions
then the step will be way smaller that if you never get the habits of managing
your analysis as a package. But of course the sharing is a key, but I think
this is a distinguish question.


## Why should you share your R package?

Again, a major question.

You have expertice in your filed your are developing methods,


Then the questions is where. So there are two main repository:
[CRAN](), []() but also the [forges](https://en.wikipedia.org/wiki/Forge_(softw can see many bad reason such as adding lines to myCV are)) for instance Github.

I had previous experience in creating package actually I have a couple
of R packages that are on GH, and so far, I think that's where they should be:

- [inSilecoMisc](https://github.com/inSileco/inSilecoMisc): a set of ultis functions, a functoin that I will likelhy use in the futiure,
I add it here

- [burningHouse](https://github.com/KevCaz/burningHouse): set pf fucntion to rpeproduce analaysis we did [for this paper](https://www.frontiersin.org/articles/10.3389/fevo.2017.00175/full)

There are on GH to share reproduce but not meant to be use by too contextualise or just not though enough to be tunr into a package so
there are


CRAN does not reflect quality of R package which leads some people to coplain
and [Kurt Hortnik, CRAN maintainer to discuss whether there are number too many packages on the CRAN](http://www.stat.tugraz.at/AJS/ausg121/121Hornik.pdf)


>  In fact, packages can be employed as “containers” for all kinds of R extension
material, such as data sets or documentation (manuals or books): because packages
are versioned, keeping the extensions up-to-date can easily be achieved.

I think it is however not a definition and I think when we think about


> Package authors often seem to prefer copying code from other packages than
depending on these, or collaborate to develop a common infrastructure. If
packages provide different solutions to similar tasks, they will evidently
rather compete than cooperate through hierarchical dependencies.


(note that I can tell you now that people who review your package also give you valuable advice!).

https://cran.r-project.org/web/packages/

## How to proceed?

Below I give a very brief description of how we proceeded for [rcites](https://cran.r-project.org/web/packages/rcites/index.html) and
try to gather useful resources. Before starting writing a to have a look at
resource that dealt in depth with this topic. I remember that I started
by reading ["Writing an R package from scratch" by Hilary Parker](http://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
that helps me get started and I then then read [R packages by Hadley Wickham](http://r-pkgs.had.co.nz/),exhaustive and very pedagogical. Last but nor least remeber that  all technical details [exhaustive documentation](https://cran.r-project.org/doc/manuals/r-release/R-exts.html
After 3 years of experience and a couple of packages, I do not frequently have
to look at then anymore, but I always find my answer if the question was not
ask on stack before!



### Local development

I personally use the [devtools](https://cran.r-project.org/web/packages/devtools/index.html)
package developed by Wickham and colleagues that make you life really easy
with package. and basically explained with the book. By the way [version 2.0](https://www.tidyverse.org/articles/2018/10/devtools-2-0-0/)


### The *devtools* packages

This is the R package you need to develop your own R package efficiently.
Hadley Wickham and colleagues have cleverly automated many steps for creating R packages in different packages that are used by *devtools*.
Let's say you have a bunch of R functions. What you need to do is to make a folder called **yourRpackage** where you edit a file **DESCRIPTION** that [describes your package](http://r-pkgs.had.co.nz/description.html).
Then, you must create a subfolder named **R** where you put your R functions (usually with a filename extension "*.R*" ) and then put all your R functions within.
Before going any further, you must document your functions.
To do so at the head of all you function, you must use a couple of lines starting by **#'** that will be used by *devtools* (via *roxygen2*) to produce the documentation. The basic syntax is:

```
#' @nameofsection  (e.g. @return, @examples, ...)
#' what you need to write
```


To have more details, the minimal example from [Hilary Parker](http://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) is well-chosen. To go deeper, look at [what Hadley Wickham wrote](http://r-pkgs.had.co.nz/man.html). Once your function os documented, you simply need to use 2 functions, like so:

```
load_all("path2yourRpackage")
document("path2yourRpackage")
```

The first function will load all the functions in the **R** folder, the second will create the folder **man** that contains one document file for each function based on what you wrote.
Those functions check wether your package is in accordance with the architecture of an R package. However neither your code nor your examples are tested.
Therefore, you must strongly benefit from [testing your package](http://r-pkgs.had.co.nz/check.html).
One first thing to do is to use the function *check* of 'devtools' package.
Also, thanks to the [*testthat*](https://cran.r-project.org/web/packages/testthat/index.html) you have a simple unit testing system.
I do not take advantage from this package, I rather use Travis as explained below.


### Github + Travis + Appveyor

[Github](https://github.com) is becoming an inescapable tool for developers. Even without collaboration Github is an useful way to work efficiently.
It offers a place to save your work, see clearly your progress and share to everyone your achievements.
If your are not familiar with Github, you can have a look at the [wikipedia page](https://en.wikipedia.org/wiki/GitHub). Then, if you are eager to use it, I suggest you go through the [users documentation](https://en.wikipedia.org/wiki/GitHub).

For an R package, there is one important extra asset: people can download and install your package using functions *install_github* or *install_git* of *devtools*. Even for your-self this is useful: once you have pushed your package to Github, you can install the released version through this process while keeping the version under development apart. Then, anytime you improve your package, you can test and document the new functions, make a new commit and so on.

Even better, for each commit you push, a series of automated testing code can be made on a dedicated server. This is the magic of the continuous integration service [Travis](https://travis-ci.org). A couple of minute after pushing the new commit, you receive an email stating whether or not your package have been built with success.

To start with Travis, after signing up (with your github account), you only need to read 1) [the thin documentation for complete beginners](http://docs.travis-ci.com/user/for-beginners) and 2) the details regarding the [R language](http://docs.travis-ci.com/user/languages/r/). Then you must decide whether or not using Travis for your projects.
You will likely notice that Travis for R language is community supported. Therefore, we are indebted to Craig Citro, Dirk Eddelbuettel, Hadley Wickham and people that contribute to the [r-travis project](https://github.com/craigcitro/r-travis), so thank you guys, it helps a lot!

### Other great resources

https://www.r-project.org/dsc/2017/slides/R-hub.pdf

https://github.com/r-hub/rhub

https://builder.r-hub.io/

http://blog.revolutionanalytics.com/2016/10/r-hub-public-beta.html

https://github.com/r-lib/usethis


http://web.mit.edu/insong/www/pdf/rpackage_instructions.pdf

https://github.com/r-lib/pkgbuild

### License and Version of your package

Two last points to conclude this post.

First, you may wonder what kind of license you must pick up for your package.
In this case, I recommend you to go and visit this website:
["ChooseALicense"](http://choosealicense.com).

Also, to chose the version number of you R package, I recommend you to follow the recommendation of [Semantic Versioning](http://semver.org). This will make the three numbers you add to your package name meaningful while others make the [version number converging to pi](https://en.wikipedia.org/wiki/TeX).

<br/>


### Submit your R package

#### CRAN

Moreover, nobody checks that your package does the
analysis right when you submit it to the CRAN, it would be impossible to
manage  right, instead they check if your structure of file and your code are compliant to the numerous tests included in `R CMD INSTALL`!

#### Ropenscience

Not all package before CRAN


#### JOSS

A publication

###

On CRAN JOSS Ropenscience for review (beyond the technical details).

https://simplystatistics.org/2015/11/06/how-i-decide-when-to-trust-an-r-package/

https://cran.r-project.org/web/packages/png/index.html
