---
title: "Make your plot Hylian"
author:
  - Kevin Cazelles and
    David Beauchesne
date: "`r paste0('April 14, 2017  -  last update on ', format(Sys.time(), '%B %d, %Y'))`"
output:
  html_document:
    include:
        after_body: [footer.html, disqus.html]
---


<!-- `paste0("2017-04-15", Last update, format(Sys.time(), "%B, %d %Y"))` -->

<br/>

Here are the 5 steps you need to make your plot a Hylian one!
**May the triforce be with you**!


0. R Version

```{r}
sessionInfo()[[1]]$version.string
```

1. Download the [*Triforce* font](https://zeldauniverse.net/media/fonts/)

```{r, eval=FALSE}
session.Info()
```


2. Open R and install the `showtext` package if not already installed:

```{r, eval=FALSE}
install.package(showtext)
```

3. To see the list of font available locally do so:

```{r}
library(showtext)
showtext.auto()
font.files()
```

4. Add the *Triforce* font to your session:

```{r}
font.add(family = 'Triforce', regular = 'Triforce.ttf')
```

5. Here it goes:

```{r, fig.width=9.5, fig.height=7}
par(family="Triforce", las=1, cex.lab=2, cex.main=2, mar=c(4,5,5,0))
plot(c(0,1), c(0,1), type="n", xlab="X-axis", ylab="Y-axis", main="Hylian Style - Link must be proud of us!")
points(runif(7), runif(7), pch="*", cex=2)
points(runif(7), runif(7), pch="$", col="#347AB7", cex=2)
points(.1, .1, pch="%", cex=6, col="#347AB7")
```
