name: Check build

on:
  pull_request:
    branches:
      - main

jobs:
  
  windows:
    runs-on: windows-latest
    steps:
      - name: install Hugo and Pandoc
        run: choco install hugo pandoc
      - name: Checkout Repository
        uses: actions/checkout@master 
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install R packages with renv
        run: |
          Rscript -e "install.packages('renv', repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "renv::restore()"
      - name: Build inSileco Blog
        run: |-
          Rscript -e "blogdown::build_site(build_rmd = 'newfile')"
          Rscript -e "blogdown::build_site(build_rmd = 'timestamp')"
      
  linux:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install apt-get packages
        run: |-
          echo "Set disable_coredump false" >> /etc/sudo.conf
          sudo apt-get update
          sudo apt-get install -y hugo libudunits2-0 libudunits2-dev 
          sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev r-cran-ncdf4
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install R packages with renv
        run: |
          Rscript -e "install.packages('renv', repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "renv::restore()"
      - name: Build inSileco Blog
        run: |-
          Rscript -e "blogdown::check_config()"
          Rscript -e "blogdown::check_content()"
          Rscript -e "blogdown::build_site(build_rmd = 'newfile')"
          Rscript -e "blogdown::build_site(build_rmd = 'timestamp')"
