name: Check blog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 11 * *'


jobs:
  R-build-blogdown:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build inSileco Blog
        run: |-
          Rscript -e "icons::download_fontawesome()"
          Rscript -e "blogdown::check_config()"
          Rscript -e "blogdown::check_content()"
          Rscript -e "blogdown::build_site(build_rmd = 'newfile')"
          Rscript -e "blogdown::build_site(build_rmd = 'timestamp')"
          tree ./public
