name: deploy inSileco blog

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  schedule:
    - cron: '33 3 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install apt-get packages
        run: |-
          sudo apt-get install -y hugo libudunits2-0 libudunits2-dev
          sudo apt-get install -y libproj-dev libgeos-dev liblwgeom-dev
          sudo apt-get install -y libgdal-dev r-cran-ncdf4
      - name: Use cache
        uses: actions/cache@v1
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install R packages with renv
        run: |
          Rscript -e "install.packages('renv', repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "renv::restore()"
      - name: Build inSileco Blog
        run: |-
          Rscript -e 'blogdown::build_site()'
      - name: Deploy inSileco Blog to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: blog
          SLACK_COLOR: '#3fb3b2'
          SLACK_ICON: https://github.com/inSileco.png?size=48
          SLACK_USERNAME: Bobot
          SLACK_TITLE: ':robot_face: Message to humans'
          SLACK_MESSAGE: ':heavy_check_mark: Blog updated and deployed'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

