on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install apt-get package(s)
        run: |-
          sudo apt-get update
          sudo apt-get install -y hugo
          sudo apt-get install -y libudunits2-0 libudunits2-dev libgeos-dev
          sudo apt-get install -y libgeos++-dev libgdal-dev r-cran-ncdf4
      - name: Install Dependencies
        run: |-
          Rscript -e "install.packages(c('remotes', 'blogdown'), repos = 'https://muug.ca/mirror/cran/')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://muug.ca/mirror/cran/')"
      - name: Build inSileco Blog
        run: |-
          Rscript -e 'blogdown::build_site()'
      - name: Deploy inSileco Blog to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public

