on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '0 0 11 * *'

name: Build and deploy our blog

jobs:
  R-build-blog:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release', cache: 'true', cache-version: 1}
          - {os: macOS-latest, r: 'release', cache: 'true', cache-version: 1}
          - {os: windows-latest, r: 'release', cache: 'true', cache-version: 1}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Build blogdown
        run: |-
          Rscript -e "blogdown::check_config()"
          Rscript -e "blogdown::check_content()"
          Rscript -e "blogdown::build_site(build_rmd = 'newfile')"
          Rscript -e "blogdown::build_site(build_rmd = 'timestamp')"
      - name: Deploy inSileco Blog to gh-pages
        if: matrix.config.os == 'ubuntu-latest' && matrix.config.r == 'release'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
