on:
  push:
    branches: main
  schedule:
    - cron: '0 0 11 * *'

name: build-and-check

jobs:
  R-build-blog:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build blogdown
        run: |-
          Rscript -e "icons::download_fontawesome()"
          Rscript -e "blogdown::install_hugo()"
          Rscript -e "blogdown::check_config()"
          Rscript -e "blogdown::check_content()"
          Rscript -e "blogdown::build_site(build_rmd = 'newfile')"
          Rscript -e "blogdown::build_site(build_rmd = 'timestamp')"
